apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-data
  namespace: manga
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
