apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:AseJyMfEp8jCcEe4mjunUvQ=,iv:2q/EAiGGKtutErsbJUjp3CoD6DVSqWT8VxCrujiptlM=,tag:rEoFcF0JDNMcMmf4M7igMg==,type:str]
    client_secret: ENC[AES256_GCM,data:XrEEjOJx0moBuspnGzUAndL/aVkHjGvBTs1sDyZMzkR6F4IbH/9H53seqXRVwXjogO0AU4OeVB8v7K+jwrd/tA==,iv:A6+OcmEtW+MMu0sJc2pDsSOU3ePm0QcR0G5tqtDMHpw=,tag:GO+G0TR+MyyMda60DpR1Pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbGo2T2I4SC8rMmFIbUZY
            eVFyYVJCeXh0WUJ5SXdibmxoaSt6eGMwdFZZClgzaWkvMExnaEpoVXEvQXFIcVp3
            dElnRnpTbVVqL0g5WkpGOU1WMjVFdVUKLS0tIEhDQjc4bGdDb3MwQW5kZ1BtQS95
            ZWJ3eWRJd0d1TmRPSnQ2NXZsS3R0aEEKl8Skw9DP2LxsQxWMItXGkHKvxXDffQbD
            ByXlx2uEqR8bAD4V+cUI+4lswKy+kFTR0mnhIEILxrPLUAb24Kkvhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13t2y9dy344ss05kr0ysgvl42xgg6wkmzw5cgnrdkjea6x3tftdnsmy2tmh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RXE4MjU1RUpCSnVDQURy
            V2pEQ1RHTUI5REtmdCtqbWw1VEpKSUpLMndFCjVGaUdGelRpMWFNTUQwclFvNnpy
            REIvdjRwR2g4aVBFVGt1bkJqQ3JpdDgKLS0tIHBIR3M3d1UwOFBUNVo2bzZld0hD
            SGZoVlF5SzhXeGUzbmljdUwwOFYwc1EKHj1CSF3R6lZ58nCcDp4A2t/Z4TEBXE29
            CNBUYcHrIrne45+k/l7skBQXd8wlpk734GMIVK/IAQ7pTm+EWMejEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ucecue6w6dvdmyyhmqh6uxwf6xazymy6gynl79kkufwdsrzlf3xqc6c7ns
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbEpwQy9LdHNIcTVsa2M4
            eGphYkcyeGcwditFMEpXOUlxOXB2WUI0NERzCnZ5SkdPbE5rcXpqNTJjc2pLRXpT
            STMrc2NMVWpPOGNaS0s3eXI4QkErbzQKLS0tIDRGVVJKVmZ1NWZpcVRzcWQ1aXVw
            Uzh1UzVlaEhlSHI5clNtazFqVkIyVFUKe71zzy65cspkermqnhyYkplMfsrAFIud
            rmy+KHRLF0/RwswVyW6ovo9yBgaX1DL/D+TOv+UytF782KVlDoc/vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cgg6ss48uz6fqxegj6l7lmrzftca0kvhuwas5d6h2saxr46ewq4s7x65tj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd0hUeWxEMTd0NU5GVHdN
            SDJydzZMMVhucFFOSjFVSUNQNko4bHB4Qlg4CkVtSktiUkdsZHEydkJOdERtR2ZJ
            M0RpSG1tY1hSL21aSE1EV01UM1pwL3MKLS0tIEdxUXY4QVpPUzI4elRpSGtLVmJ5
            WUlzWjB3OFpnY0QwUU9zSzFYMWZUdmcKNQIkK4YiPihV72zitBwdJkaHCE1D0hqz
            8gLaA9V30vAnR4Ox0UkQlPK/GKrqT8Rs9keL3+jQPd+XMb8U1ZPAPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjsmhfc25qak472y60cmyr29anvk4e44ay3qtr030kj95wzmru9qqjw5zs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T20:47:20Z"
    mac: ENC[AES256_GCM,data:zEF4D4+i/PrC70dzG9us/d1ZQvlIuwBvyQPxmNkNOBPX8qP6PnrQMXY49Lu9oItK5cy11oZ/i5CY84hk6xYb1iP7HOsllf385AEbqrMH/szDDfdpxXAIlrl2Ta0o7NbiNfXU4ADD398DMuY+r/Gu/y4JfMdSHtHcoS2VqrKwcvA=,iv:9vkAw6hogYi1bClmPgXMjJ5E06j0d18FGcnG1AIoZQY=,tag:RYq73hea6L6lew+qEULZng==,type:str]
    version: 3.13.0
