apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:AseJyMfEp8jCcEe4mjunUvQ=,iv:2q/EAiGGKtutErsbJUjp3CoD6DVSqWT8VxCrujiptlM=,tag:rEoFcF0JDNMcMmf4M7igMg==,type:str]
    client_secret: ENC[AES256_GCM,data:XrEEjOJx0moBuspnGzUAndL/aVkHjGvBTs1sDyZMzkR6F4IbH/9H53seqXRVwXjogO0AU4OeVB8v7K+jwrd/tA==,iv:A6+OcmEtW+MMu0sJc2pDsSOU3ePm0QcR0G5tqtDMHpw=,tag:GO+G0TR+MyyMda60DpR1Pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZTVwTGc5b1pNaTNLVlEr
            RHh6UEpKR2tNaHpRcEMybm56clVSOFpvY0NvCm1DT2VPOFBuSU1xZXdoVUJTS1lw
            amNxWFV6bUJXVHJJd1Q0cmJ5VVpybzgKLS0tIDc3UjV4a3ZMNmRZSFBKa1lSZGdP
            Wk9OMTNJSjZvTW96ZzlsZk56NXg4ekEKT4UjgSjeBwFoqfrgiPu5SkFaxUTCfTs2
            GwwvMNc7LF5ybVx6pg++Q5BfWZ8KnfbBYrpPakpbXGo8FjdsiJuzNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13t2y9dy344ss05kr0ysgvl42xgg6wkmzw5cgnrdkjea6x3tftdnsmy2tmh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYmhYOGxiZ1luUUMvVlVI
            LzNZZUIzcnpYRmFHc0d0bG1uaEJZQjcxZDNBCnBQd0pmRjJRbUV3enl2c1lCcElw
            ejdmRHJ2RHJBSXB6cTduYWxXOCtLb3MKLS0tIFVjckd4SjNVbWJJcHh3cEpuMEFU
            akp1ZnJhanhUNXJJQXdiTVFFWXNWQWMKD2HdzL/rWONTrYIKUYhrmb/83KBaDByl
            CrLKmo7+KLlMN/MMfTxcjtL4OOg/jGfMA6W9OfHp+8wqaGnQwvPWDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1562ws2s8xya8dhur9cm5k8wt8a4vdn6vwz5sdqawv2gy6xws74mq0q9cdt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0pPbEdaRDhvOCt3bUEr
            Z0RZSHUyR2YzS1NBVmVIalB0N21tUk5rSXg4Ci9GdWFNb2hHNVpsbGhMUzNVc1dC
            Skl3WDMyTXVMeTVDVFRaNTZORTRpbHcKLS0tICtLKytuOVFDR1VlVFNGaTBQb1Rz
            M21CSEJvK1lsZW5NZC9EZExaOG9vZ1kK5X67Czut0Fb5muBMqB90K3WKhVR6itfK
            +F04XNlqdRtVVCicyFBRrkK9D5bUgl9iCswJl9JvNtDg+AUdu6FbKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cqv6v8fmghfzul8x44rjfrk8x8lp7k8xv76vx7av8ykuffjv9fuqptw5eg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TkhtaUpSUGNaSFlvUHkx
            MGhTdVFxaGRtUUx2eGVJZHVIbHVBZEZBTGdnClJoWWJObTBXNjFmbmJGMUdCbWVO
            b3dBK3ZPZUdEMTBOei94U2NyQnNkTDAKLS0tIDFiTmRCQWphWlhJTWt5NnNmQU5u
            bHUyUC9RWDJxWFpZK3MvNm5xRFk5WUkK79/2ZR49oBx+kymHhn55oEnnB7u6LeG3
            6S9vn5vvAWJqlVcgDKPx6FZj6UleQVX5SV3aNERcLA+jbnMkt6VGfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17l2c5wqk9lgq79kwkgw3hgkuklun5sn5rmy8j84gsj4f630psytq8ugeqe
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T20:47:20Z"
    mac: ENC[AES256_GCM,data:zEF4D4+i/PrC70dzG9us/d1ZQvlIuwBvyQPxmNkNOBPX8qP6PnrQMXY49Lu9oItK5cy11oZ/i5CY84hk6xYb1iP7HOsllf385AEbqrMH/szDDfdpxXAIlrl2Ta0o7NbiNfXU4ADD398DMuY+r/Gu/y4JfMdSHtHcoS2VqrKwcvA=,iv:9vkAw6hogYi1bClmPgXMjJ5E06j0d18FGcnG1AIoZQY=,tag:RYq73hea6L6lew+qEULZng==,type:str]
    version: 3.13.0
