---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  encryptedData:
    password: AgAUV1mS0ymBwc7WhzJeNPuc12wJxg5f6KBzvvRka6UbRI/NFDtAhvU0EXtGtJ5XOXkbblubgLA8KHeDizQep6UeYakkP/2axPgXrA+2Gb2VAQNkYMCpU9U1KmOEVT8fn1XxWE4U6tWI217OSo0GYR400V36uw57RARzEdiFzN6RufmRhCr5XkHoKq0svNxWujoJ2sRGfFFKVSFquDWR8b5Sx/jZr9SQ8W6u5HbPzNCu+iTUhLAlFTFon2K8rnGEFb8j8nVCc8hPqF2ZJZF9BGZT9Z/V+vFM6hQJWVUumQ55dEYq5W/nBb4yLu6VrKYJeRt6lFki/luPg9q1wPrhr8/FXDLgFZTta1ha3cO6C4mW4JGUClngw8Cor3oZMFLXmPgbDlLM3s8suHNtCmKvhJSSWCQAEYbR31euOvZSBs4otxA/3yjETMXS1Ya+QmYGfziltS4mTPgUk16uX8CW7wfnC4ikgXnoZcglZ0G/xNUrgKA7fFaquTCXRfGdeYxqr39RwSNXfPY5Mp7VX7QZeIUTO5Tr6UywTj14xeddF10Fy+lARDTW9XpWXbyADHUr6XvHH2ygSNshfwCMdbpV3kwNvZ1XZTtlD68D3DI6OO7VQgHp8uIqf9PpPYTXzG75RvC0ryYK9yE3ok/D4wJTauxqoQdzWIIeAmZToQR9BR/IcshVkQAc++CpLexYle0kYYWmhEN1cOos8OAKClymuajrpJxL2lHy9jlRmqHlEqi8lF7yroqcXic0HNy8t8VCEQATO0u+2FnAqea07+cp0nkW
    username: AgCOERo2b86WGoLfUb8sB7mAEow9ZTY5ohMA48gt2B5gxI7lbchQSj7lYQlrT+BBhNOOj+vCZNKEO4gcdwEajsDluu3ADR5x18sQenIf4Y44DuoEosMHvHCCKfVB1koGLGIiDcHowhxMCEvqF+r6L9wifI2LobzadidOmoLEyimjoUxBGnYVBBXp06R8bHqjLXG5erqxxbL5FtNw0dFiJzocJBWPGcsTWLx7ytp5MqYAilPgWcrv8aEQ6sZslXzNPwkllYmyuDlSEKnmFGFpinLSBu0j+eE5V/LCyqJXREVI54keM7SSJR1VoFGaSL3FETGuaYoRLLuWOE5LExSAW2xCkyTfBQMt2NP1FzPTDeySUtbbEn5VjUMKi1g3TEIL2CLhNceZ09ny3xMzGEI0Ni+ZNaDqyhcG15bhrNzg8m5yP9avjKOqdyYELwlQbpn7lcgYjB4ZBS9xP0tsHWV6mSGyEjSg82sxG6uinjhmO4ftpT/P6/YvbBzQdDKztZIueqfeQJgijr1r/2qfOmtNC6+1G4i/h2vegZU7tSER8EHUPqLRgsCaFgy4ncks0mi0UqVK2Ugz/uU8y8Cr5d78L4P3BKmfOicXO3EIENZC8Hjx4lAAxKYt30WCwvPNHSTJCWkJ9YlwRcHwkGoCiDXrL4gn+R1lhK5MW2vKWs9cVJH61FqsAn3MbwQ2IdAYzJ3rhQEBn/6yqjg=
  template:
    metadata:
      name: immich-postgres-user
      namespace: immich
    type: kubernetes.io/basic-auth
