apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
data:
  conf.yml: |
    pageInfo:
      title: Hemera Homelab
      description: Jumping off point for homelab services
      navLinks:
        - title: Github
          path: https://github.com/edeneast/hemera

    appConfig:
      theme: dracula
      layout: auto
      iconSize: large
      language: en
      statusCheck: true
      statusCheckInterval: 60
      # disableConfiguration: true
      # hideComponents:
      #   hideSettings: true

    sections:
      - name: media
        icon: fas fa-photo-video
        items:
          - title: audiobookshelf
            description: audiobooks and podcasts
            icon: hl-audiobookshelf
            url: https://audiobookshelf.cerberus-tilapia.ts.net
            statuscheck: true
          - title: immich
            description: photo and video backup
            icon: hl-immich
            url: https://photos.cerberus-tilapia.ts.net
            statuscheck: true
          - title: manga
            description: suwayomi manga reader
            icon: >-
              https://github.com/suwayomi/suwayomi-server/raw/master/server/src/main/resources/icon/faviconlogo.png
            url: https://manga.cerberus-tilapia.ts.net
            statuscheck: true

      - name: development
        icon: fas fa-code-branch
        items:
          - title: forgejo
            description: git hosting
            icon: hl-forgejo
            url: https://git.cerberus-tilapia.ts.net
            statuscheck: true

      - name: operations
        icon: fas fa-server
        items:
          - title: grafana
            description: metrics and dashboards
            icon: hl-grafana
            url: https://grafana.cerberus-tilapia.ts.net
            statuscheck: true
          - title: prometheus
            description: system statistics aggregation
            icon: hl-prometheus
            url: https://prometheus.cerberus-tilapia.ts.net
          - title: flux
            description: gitops operator
            icon: >-
              https://github.com/homarr-labs/dashboard-icons/raw/main/png/flux-operator.png
            url: https://flux.cerberus-tilapia.ts.net
          - title: longhorn
            description: cluster storage
            icon: hl-longhorn
            url: https://longhorn.cerberus-tilapia.ts.net
            statuscheck: true
