---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAFGqc37BKECTbmcnT5i0Xl2ZW6hs1hRT6f2H4jhjM4XaRNTagn+gXSXdVdZnKHxV3Sa2+WHH0a/zDP/SYgkCSwx8anbuGiUTbcrXTdCngag7ItCfo5Hcjo3peBZByyWYLZsLhXPJF0at1jbnCxF89yJzmGEcIZd8cD1iFcWims6v7k5LyYYDwl3Iq83Oc+bZmo84YVy2udRLMSwjfe4vGdm6kTqessnMn4lv/+F4x38uHJgwnveGtWD1O6fObZK+nGjiQWlnTqm8SNDDt39wF13E7ptm8nrWeDZ4pn/tFUC5Tdn1KwtjVVXYKPzi896ZFJrzVDNcQ8iEm0GUFbraeXu7fKnUPT6vNOqC4TVrRnUh7X6bxkoAZQtDcLKxKwDqAWqEHvYzqcD9b31TzXGL3bQqWE3InSCSJBlMZB/F/IC5OnkC3fQZVt6N+rZvkaWhLNIBqzrW2AUhtV/heRwRV3LhhtrnlL/r/yDfT02O/4sLmO1ek8jIov8fqMWGhsaJ/VFmQjaVZGUVZ+tTAUum7U8yCNkqULHtSs/eboGhUMsaz6JcZqqexocpIG+MMWHjKbgMtV0gcv+7cqj0qvf2kajlAAssXm/O3jKHAXcjg9uhN/IxBYgM1BDNeXr1piZfHAk9Pw123QeWwXRsoXZ/XInQFTMpBNJsIN1oj5fwkDSBuv8aA5sY7tbC5vcmVclLogBZapO1HwWKvjwLUiPfvVoQ==
    client_secret: AgAgl5UU6IBeldqMEgKgvHKbwSMpQTby8qhvreIvYjF0ZbJrR3lS5t3cIPEwuhFXn3jGY0ArhTpJnfUqP3wIU4swgVo+pnMtzYyqATh9oguEfmj4jNziy7W6vWpPlBmrT0xhKZ9oNVfmSq6+Ofsvhc4qCpkpNLEX4pcL8OrTesPMNy/WZxS8TygocNv7pvg79jYmhXwu17KTaIZS87bIDdLlLM1gxn7KLdZXdnmnQ/0EQHGofiFfZQzSTG1GN1xMcbsc7cms22aOVCho5WrHZSqynYjSJE87+I/vP00Sp9TiWQeFd4aUzZt6X+CGn3uw7hGNpNEjeP23IBNMmJAGVqxslZPNRfBpJ0qbzhKq/X0IU95IConALz2H0EONzkmpujfK5GKPsYEDsFgK0e0UvPqWumUy/25v2xziWMwi7tbDlMA6i0xzHAcFuiB34S/XyreGwdjc/dy5TEwPqz9livCvJrSiljvUN0MenbsC76qIMc+9bf+nj2SV6+Iq9j6VRu5qxZsW5UC5z0yih6QZnt4AOsdyStF9HmRIH9zZ7snKezXL/Emly1MLfZzfz9pMK1k4/svMz1TsbuKP1igReD3IZuVPoKMsDImvhWNBwFSNSvj1L/gDNIvqDdAsvciLsKqCv3MAX/IxJBXtkc/AmYYvaJP11kuoi4z5JRWYS0+mqj+UUaE74XkSz6JK69dbAlQS2NbdwBCqXERNKamQ/h6EPrUPujfYL8kn4gHzS3taAv99bkoaaOkFh4dbHsrjPs3mOPyiiqCPqHjYG/BH6813
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
