---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgres-user
  namespace: forgejo
spec:
  encryptedData:
    password: AgA4PaesGu47nr9wjTywzHPDpS0o1piOCSu2BAJbJOL84IIe3ZCX4hRXuIgepWp7/EjWMvj7G52noOKzYFd1RXcTrorGKj+pwoMFyq20N1L1yGbgSAYM8tC1brAT3E+j1mQnULlRmN6M+8i3nZoFheBIlML54CV+jL7Ns7V+hZg7HIlDBe0rLWyHhjYUc43731MMZJkx+3ix9aYXXNF4PeDd5L2McnkqUOJRUDgr7W3MhoxPkwunk3uOY/kQzY5KMjHjBY7I6dO7vDsTmBBjc4hWdUPpcc6NZCcu4+synKnOsmzmBMZphXc10UdnmMmQEUieQ0rqD10ILq6hYuIL0EDSeH0CZq0cF0ZGcF6cClbl/WsVntD5mwuAmdFHGjwbI/C0F2GRi+692yYz+dw2k1xJEKtZSlmDDdsHnnWOnOweFPmP6OYdR3J+GiRv/fSXu0WdrjemSaDaShSUk8tLD7egB6FzmsId+b03ruLoW6Z/MIrspPggL5ZhkRxJYaHJ+Nuw66GxKvEtLHOhFhqs1bN+4bCST2NcsJ9rLhH4R4ddkxP/lMqpKyylekgAru4FivEHH3uVhmFlKz44jh0yh+viX16t0nYjJOCVodRPGWJhI8JVyfXI69DGyHF3WhlwTBoSxuujHGTj6aX2cMjLWlLA6NngBHh6LgD1LIQeSKfzpH4r3hWbJdomkfa778Uyuh8nQIjN9lmQba+YDu6extcrjSci60i6vljpFhQ6zCPvL2N4auJGK0Ip7vCuoG8aB0I=
    username: AgAdK38EMsgQhhEcMXRDe4asPquIsfLr0BLXwCZlI4GU/JoJB3xw1jO/ups03qvelhWp9E2UXkWXTGkGgnDEr6PmJqXx4w21JzMbl8gQQQqfJqKslppRrsK+bPbYwE6H91IQFZy0Ry8HP+j3aufRxtkcY9yt2o3slSixcGzdc1Qi0iuOCyoWq+dAeiWOGH44Efw8UxC5cFuKZkJ/J/YOktC0FblrdsR2s6LPXaaFXnv4+Z3QDWM/1mIMv+7UhkoRHoPBdym9wXB1V9e0duuYt90fFgQUl/LZjaawvy34AgNUit3tUr9n3A85R5VfCgsvQtS+IiAxa7NJexjiQFQ9JOmRVNOL1AhBadQgWVp2j9lcR4wwbxBa8zNKUTtlQ+AnYzFyzIh21pnDD/6LxHNQc0G0ABc8WiIeKtn/99w07nVlk/Dkeb494M1410SJAMPdiTPZSZVIHSw+5OoDkgcrBEUNJ11cDEHP9PIYpjiRktMloQpRvhc6k6rCbA5SN59B2xKBFWgJCv4W/xMy8GKCDi0GuuD+8cLmYhM70PAN6My9MXHFjImUPlTFMOkAUOmTGsMTnBiBngkaHA986BRbu8IS2jpJpe9AjaJwxsFNFHDha9qmvWsYB6vvjaoub6AFMKcItqmAXlykaC3W5PBm2Ys6vzYD9MUpSp9luGFAG4Yy1oLJH+w/nEDnR/Rk1GY56rFy0pR2SNqW
  template:
    metadata:
      name: forgejo-postgres-user
      namespace: forgejo
    type: kubernetes.io/basic-auth
