apiVersion: v1
kind: Service
metadata:
  name: vault-smb
  namespace: default
  annotations:
    tailscale.com/hostname: vault
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vault-smb
  namespace: default
  labels:
    kubernetes.io/service-name: vault-smb
addressType: IPv4
ports:
  - name: smb
    port: 445
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.2.116
