apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hemera-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: git@github.com:EdenEast/hemera.git
    targetRevision: argo-migration
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - Prune=false
