apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hemera-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  generators:
    - git:
        repoURL: git@github.com:EdenEast/hemera.git
        revision: argo-migration
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:EdenEast/hemera.git
        targetRevision: argo-migration
        path: '{{path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - Prune=false
